// <auto-generated />
using System;
using InfoTech.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfoTech.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241108085235_CreateAndSeedProjectsTableInDatabase")]
    partial class CreateAndSeedProjectsTableInDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InfoTech.Models.AboutTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AboutTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tag = "هویت برند و طراحی"
                        },
                        new
                        {
                            Id = 2,
                            Tag = " راه حل های بازاریابی وب سایت"
                        },
                        new
                        {
                            Id = 3,
                            Tag = "داده های دانلود نامحدود"
                        });
                });

            modelBuilder.Entity("InfoTech.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Block")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Block = "0",
                            City = "شیراز",
                            Location = "جاده شیراز-سپیدان, گویم",
                            PostalCode = "2547896548",
                            State = "فارس"
                        });
                });

            modelBuilder.Entity("InfoTech.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageId = 8,
                            Name = "برند نو"
                        },
                        new
                        {
                            Id = 2,
                            ImageId = 9,
                            Name = "برند نو"
                        },
                        new
                        {
                            Id = 3,
                            ImageId = 10,
                            Name = "برند نو"
                        },
                        new
                        {
                            Id = 4,
                            ImageId = 11,
                            Name = "برند نو"
                        });
                });

            modelBuilder.Entity("InfoTech.Models.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "abbasmasoudardakani@gmail.com",
                            Status = 1
                        });
                });

            modelBuilder.Entity("InfoTech.Models.HeroBanner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmptyButtonAction")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmptyButtonCaption")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FillButtonAction")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FillButtonCaption")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.ToTable("HeroBanners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "آموزش شکلات برنزی و ارتقای عمر محصول را به دنبال خواهد داشت. همه می خواهند تکالیف خود را در دوره انجام دهند، اما اعضای مدرسه به آن نیاز دارند",
                            EmptyButtonAction = "/Customer/Home/About",
                            EmptyButtonCaption = "بیشتر کاوش کنید",
                            FillButtonAction = "/Customer/Home/Contact",
                            FillButtonCaption = "با ما تماس بگیرید",
                            ImageId = 4,
                            Tag = "بهترین شرکت",
                            Title = "کسب و کار ما را دریافت کنید بهترین راه حل"
                        },
                        new
                        {
                            Id = 2,
                            Description = "آموزش شکلات برنزی و ارتقای عمر محصول را به دنبال خواهد داشت. همه می خواهند تکالیف خود را در دوره انجام دهند، اما اعضای مدرسه به آن نیاز دارند",
                            EmptyButtonAction = "/Customer/Home/About",
                            EmptyButtonCaption = "بیشتر کاوش کنید",
                            FillButtonAction = "/Customer/Home/Contact",
                            FillButtonCaption = "با ما تماس بگیرید",
                            ImageId = 5,
                            Tag = "بهترین شرکت",
                            Title = "کسب و کار ما را دریافت کنید بهترین راه حل"
                        },
                        new
                        {
                            Id = 3,
                            Description = "آموزش شکلات برنزی و ارتقای عمر محصول را به دنبال خواهد داشت. همه می خواهند تکالیف خود را در دوره انجام دهند، اما اعضای مدرسه به آن نیاز دارند",
                            EmptyButtonAction = "/Customer/Home/About",
                            EmptyButtonCaption = "بیشتر کاوش کنید",
                            FillButtonAction = "/Customer/Home/Contact",
                            FillButtonCaption = "با ما تماس بگیرید",
                            ImageId = 6,
                            Tag = "بهترین شرکت",
                            Title = "کسب و کار ما را دریافت کنید بهترین راه حل"
                        });
                });

            modelBuilder.Entity("InfoTech.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "flags/Iran-flag.jpeg",
                            Alt = "پرچم کشور ایران",
                            Title = "Iran Flag"
                        },
                        new
                        {
                            Id = 2,
                            Address = "flags/England-flag.jpeg",
                            Alt = "English Flag",
                            Title = "England Flag"
                        },
                        new
                        {
                            Id = 3,
                            Address = "logo/black-logo.svg",
                            Alt = "لوگوی صفحه",
                            Title = "لوگوی صفحه"
                        },
                        new
                        {
                            Id = 4,
                            Address = "hero/hero-2.jpg",
                            Alt = "عکس بنر",
                            Title = "عکس بنر"
                        },
                        new
                        {
                            Id = 5,
                            Address = "hero/hero-1.jpg",
                            Alt = "عکس بنر",
                            Title = "عکس بنر"
                        },
                        new
                        {
                            Id = 6,
                            Address = "hero/hero-3.jpg",
                            Alt = "عکس بنر",
                            Title = "عکس بنر"
                        },
                        new
                        {
                            Id = 7,
                            Address = "about/05.png",
                            Alt = "عکس درباره ما",
                            Title = "عکس درباره ما"
                        },
                        new
                        {
                            Id = 8,
                            Address = "brand.png",
                            Alt = "عکس برند",
                            Title = "عکس برند"
                        },
                        new
                        {
                            Id = 9,
                            Address = "brand.png",
                            Alt = "عکس برند",
                            Title = "عکس برند"
                        },
                        new
                        {
                            Id = 10,
                            Address = "brand.png",
                            Alt = "عکس برند",
                            Title = "عکس برند"
                        },
                        new
                        {
                            Id = 11,
                            Address = "brand.png",
                            Alt = "عکس برند",
                            Title = "عکس برند"
                        },
                        new
                        {
                            Id = 12,
                            Address = "service/01.jpg",
                            Alt = "عکس سرویس",
                            Title = "عکس سرویس"
                        },
                        new
                        {
                            Id = 13,
                            Address = "service/02.jpg",
                            Alt = "عکس سرویس",
                            Title = "عکس سرویس"
                        },
                        new
                        {
                            Id = 14,
                            Address = "service/03.jpg",
                            Alt = "عکس سرویس",
                            Title = "عکس سرویس"
                        },
                        new
                        {
                            Id = 15,
                            Address = "service/04.jpg",
                            Alt = "عکس سرویس",
                            Title = "عکس سرویس"
                        },
                        new
                        {
                            Id = 16,
                            Address = "service/05.jpg",
                            Alt = "عکس سرویس",
                            Title = "عکس سرویس"
                        },
                        new
                        {
                            Id = 17,
                            Address = "process/linepng.png",
                            Alt = "عکس پروسه",
                            Title = "عکس پروسه"
                        },
                        new
                        {
                            Id = 18,
                            Address = "process/01.png",
                            Alt = "عکس پروسه",
                            Title = "عکس پروسه"
                        },
                        new
                        {
                            Id = 19,
                            Address = "process/02.png",
                            Alt = "عکس پروسه",
                            Title = "عکس پروسه"
                        },
                        new
                        {
                            Id = 20,
                            Address = "process/03.png",
                            Alt = "عکس پروسه",
                            Title = "عکس پروسه"
                        },
                        new
                        {
                            Id = 21,
                            Address = "process/04.png",
                            Alt = "عکس پروسه",
                            Title = "عکس پروسه"
                        },
                        new
                        {
                            Id = 22,
                            Address = "project/01.jpg",
                            Alt = "عکس پروژه",
                            Title = "عکس پروژه"
                        },
                        new
                        {
                            Id = 23,
                            Address = "project/02.jpg",
                            Alt = "عکس پروژه",
                            Title = "عکس پروژه"
                        },
                        new
                        {
                            Id = 24,
                            Address = "project/03.jpg",
                            Alt = "عکس پروژه",
                            Title = "عکس پروژه"
                        },
                        new
                        {
                            Id = 25,
                            Address = "project/04.jpg",
                            Alt = "عکس پروژه",
                            Title = "عکس پروژه"
                        },
                        new
                        {
                            Id = 26,
                            Address = "project/05.jpg",
                            Alt = "عکس پروژه",
                            Title = "عکس پروژه"
                        },
                        new
                        {
                            Id = 27,
                            Address = "project/06.jpg",
                            Alt = "عکس پروژه",
                            Title = "عکس پروژه"
                        },
                        new
                        {
                            Id = 28,
                            Address = "project/07.jpg",
                            Alt = "عکس پروژه",
                            Title = "عکس پروژه"
                        },
                        new
                        {
                            Id = 29,
                            Address = "project/08.jpg",
                            Alt = "عکس پروژه",
                            Title = "عکس پروژه"
                        },
                        new
                        {
                            Id = 30,
                            Address = "project/09.jpg",
                            Alt = "عکس پروژه",
                            Title = "عکس پروژه"
                        },
                        new
                        {
                            Id = 31,
                            Address = "project/10.jpg",
                            Alt = "عکس پروژه",
                            Title = "عکس پروژه"
                        },
                        new
                        {
                            Id = 32,
                            Address = "project/11.jpg",
                            Alt = "عکس پروژه",
                            Title = "عکس پروژه"
                        },
                        new
                        {
                            Id = 33,
                            Address = "project/12.jpg",
                            Alt = "عکس پروژه",
                            Title = "عکس پروژه"
                        },
                        new
                        {
                            Id = 34,
                            Address = "project/13.jpg",
                            Alt = "عکس پروژه",
                            Title = "عکس پروژه"
                        },
                        new
                        {
                            Id = 35,
                            Address = "project/14.jpg",
                            Alt = "عکس پروژه",
                            Title = "عکس پروژه"
                        },
                        new
                        {
                            Id = 36,
                            Address = "project/15.jpg",
                            Alt = "عکس پروژه",
                            Title = "عکس پروژه"
                        });
                });

            modelBuilder.Entity("InfoTech.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            ImageId = 1,
                            Name = "فارسی",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            ImageId = 2,
                            Name = "English",
                            Status = 1
                        });
                });

            modelBuilder.Entity("InfoTech.Models.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Author")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Keywords")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "/Customer/Home/Index",
                            Author = "Anathan",
                            Description = "صفحه نخست سایت اینفو تک",
                            Keywords = "Home, info tech, C#",
                            Name = "صفحه اصلی",
                            Title = "Home"
                        },
                        new
                        {
                            Id = 2,
                            Action = "/Customer/Home/About",
                            Author = "Anathan",
                            Description = "صفحه نخست سایت اینفو تک",
                            Keywords = "Home, info tech, C#",
                            Name = "درباره",
                            Title = "About Us"
                        },
                        new
                        {
                            Id = 3,
                            Action = "/Customer/Home/Services",
                            Author = "Anathan",
                            Description = "صفحه نخست سایت اینفو تک",
                            Keywords = "Home, info tech, C#",
                            Name = "خدمات",
                            Title = "Services"
                        },
                        new
                        {
                            Id = 4,
                            Action = "/Customer/Home/Pages",
                            Author = "Anathan",
                            Description = "صفحه نخست سایت اینفو تک",
                            Keywords = "Home, info tech, C#",
                            Name = "صفحات",
                            Title = "Pages"
                        },
                        new
                        {
                            Id = 5,
                            Action = "/Customer/Home/Blogs",
                            Author = "Anathan",
                            Description = "صفحه نخست سایت اینفو تک",
                            Keywords = "Home, info tech, C#",
                            Name = "وبلاگ",
                            Title = "Blogs"
                        },
                        new
                        {
                            Id = 6,
                            Action = "/Customer/Home/Contact",
                            Author = "Anathan",
                            Description = "صفحه نخست سایت اینفو تک",
                            Keywords = "Home, info tech, C#",
                            Name = "تماس",
                            Title = "Contact"
                        });
                });

            modelBuilder.Entity("InfoTech.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = "+989369043949",
                            Status = 1
                        });
                });

            modelBuilder.Entity("InfoTech.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.HasIndex("ServiceId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "",
                            Description = "بنتشسهیبتتشثهبتشئههصشبتیشتکهتثهتبشکیستبشهصشبتهثصتبشیرئنتشهقثتبیسه",
                            ImageId = 22,
                            ServiceId = 1,
                            Title = "پروژه یک"
                        },
                        new
                        {
                            Id = 2,
                            Content = "",
                            Description = "بنتشسهیبتتشثهبتشئههصشبتیشتکهتثهتبشکیستبشهصشبتهثصتبشیرئنتشهقثتبیسه",
                            ImageId = 23,
                            ServiceId = 2,
                            Title = "سیبهشتسک"
                        },
                        new
                        {
                            Id = 3,
                            Content = "",
                            Description = "بنتشسهیبتتشثهبتشئههصشبتیشتکهتثهتبشکیستبشهصشبتهثصتبشیرئنتشهقثتبیسه",
                            ImageId = 24,
                            ServiceId = 3,
                            Title = "سبیشثهشی"
                        },
                        new
                        {
                            Id = 4,
                            Content = "",
                            Description = "بنتشسهیبتتشثهبتشئههصشبتیشتکهتثهتبشکیستبشهصشبتهثصتبشیرئنتشهقثتبیسه",
                            ImageId = 25,
                            ServiceId = 4,
                            Title = "تست پروژه"
                        },
                        new
                        {
                            Id = 5,
                            Content = "",
                            Description = "بنتشسهیبتتشثهبتشئههصشبتیشتکهتثهتبشکیستبشهصشبتهثصتبشیرئنتشهقثتبیسه",
                            ImageId = 26,
                            ServiceId = 5,
                            Title = "پروژه تستی"
                        },
                        new
                        {
                            Id = 6,
                            Content = "",
                            Description = "بنتشسهیبتتشثهبتشئههصشبتیشتکهتثهتبشکیستبشهصشبتهثصتبشیرئنتشهقثتبیسه",
                            ImageId = 27,
                            ServiceId = 2,
                            Title = "پروژه تستی"
                        },
                        new
                        {
                            Id = 7,
                            Content = "",
                            Description = "بنتشسهیبتتشثهبتشئههصشبتیشتکهتثهتبشکیستبشهصشبتهثصتبشیرئنتشهقثتبیسه",
                            ImageId = 28,
                            ServiceId = 1,
                            Title = "پروژه تستی"
                        },
                        new
                        {
                            Id = 8,
                            Content = "",
                            Description = "بنتشسهیبتتشثهبتشئههصشبتیشتکهتثهتبشکیستبشهصشبتهثصتبشیرئنتشهقثتبیسه",
                            ImageId = 29,
                            ServiceId = 4,
                            Title = "پروژه تستی"
                        },
                        new
                        {
                            Id = 9,
                            Content = "",
                            Description = "بنتشسهیبتتشثهبتشئههصشبتیشتکهتثهتبشکیستبشهصشبتهثصتبشیرئنتشهقثتبیسه",
                            ImageId = 30,
                            ServiceId = 3,
                            Title = "پروژه تستی"
                        },
                        new
                        {
                            Id = 10,
                            Content = "",
                            Description = "بنتشسهیبتتشثهبتشئههصشبتیشتکهتثهتبشکیستبشهصشبتهثصتبشیرئنتشهقثتبیسه",
                            ImageId = 31,
                            ServiceId = 5,
                            Title = "پروژه تستی"
                        },
                        new
                        {
                            Id = 11,
                            Content = "",
                            Description = "بنتشسهیبتتشثهبتشئههصشبتیشتکهتثهتبشکیستبشهصشبتهثصتبشیرئنتشهقثتبیسه",
                            ImageId = 32,
                            ServiceId = 3,
                            Title = "پروژه تستی"
                        },
                        new
                        {
                            Id = 12,
                            Content = "",
                            Description = "بنتشسهیبتتشثهبتشئههصشبتیشتکهتثهتبشکیستبشهصشبتهثصتبشیرئنتشهقثتبیسه",
                            ImageId = 33,
                            ServiceId = 2,
                            Title = "پروژه تستی"
                        },
                        new
                        {
                            Id = 13,
                            Content = "",
                            Description = "بنتشسهیبتتشثهبتشئههصشبتیشتکهتثهتبشکیستبشهصشبتهثصتبشیرئنتشهقثتبیسه",
                            ImageId = 34,
                            ServiceId = 1,
                            Title = "پروژه تستی"
                        },
                        new
                        {
                            Id = 14,
                            Content = "",
                            Description = "بنتشسهیبتتشثهبتشئههصشبتیشتکهتثهتبشکیستبشهصشبتهثصتبشیرئنتشهقثتبیسه",
                            ImageId = 35,
                            ServiceId = 5,
                            Title = "پروژه تستی"
                        },
                        new
                        {
                            Id = 15,
                            Content = "",
                            Description = "بنتشسهیبتتشثهبتشئههصشبتیشتکهتثهتبشکیستبشهصشبتهثصتبشیرئنتشهقثتبیسه",
                            ImageId = 36,
                            ServiceId = 5,
                            Title = "پروژه تستی"
                        });
                });

            modelBuilder.Entity("InfoTech.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmptyButtonAction")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmptyButtonCaption")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FillButtonAction")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FillButtonCaption")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("IndexSections")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "ما در این موسسه افتخار این را داریم که بگوییم بهترین هستیم و همیشه حق با مشتری است",
                            FillButtonAction = "/Customer/Home/About",
                            FillButtonCaption = "درباره ما",
                            IndexSections = 0,
                            Tag = "درباره اینفوتک",
                            Title = "بزرگترین شرکت تکنولوژی ایران"
                        },
                        new
                        {
                            Id = 2,
                            IndexSections = 2,
                            Title = "برند های که به ما اعتماد کرده اند"
                        },
                        new
                        {
                            Id = 3,
                            FillButtonAction = "/Customer/Home/Service",
                            FillButtonCaption = "سرویس ما",
                            IndexSections = 7,
                            Tag = "سرویس ها",
                            Title = "فعالیت های ما در این شرکت"
                        },
                        new
                        {
                            Id = 4,
                            IndexSections = 10,
                            Tag = "نحوه کار",
                            Title = "پروسه کاری این شرکت"
                        });
                });

            modelBuilder.Entity("InfoTech.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "",
                            Description = "سرویسی که این شرکت ارایه میدهد",
                            ImageId = 12,
                            Name = "امنیت سایبری"
                        },
                        new
                        {
                            Id = 2,
                            Content = "",
                            Description = "سرویسی که این شرکت ارایه میدهد",
                            ImageId = 13,
                            Name = "فناوری اطلاعات"
                        },
                        new
                        {
                            Id = 3,
                            Content = "",
                            Description = "سرویسی که این شرکت ارایه میدهد",
                            ImageId = 14,
                            Name = "توسعه برنامه"
                        },
                        new
                        {
                            Id = 4,
                            Content = "",
                            Description = "سرویسی که این شرکت ارایه میدهد",
                            ImageId = 15,
                            Name = "بازاریابی دیجیتال"
                        },
                        new
                        {
                            Id = 5,
                            Content = "",
                            Description = "سرویسی که این شرکت ارایه میدهد",
                            ImageId = 16,
                            Name = "تحلیل داده"
                        });
                });

            modelBuilder.Entity("InfoTech.Models.SocialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Media")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("SocialMedias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "<i class=\"bi bi-telegram\"></i>",
                            Link = "https://www.t.me/Abbasmasoud",
                            Media = "Telegram"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "<i class=\"bi bi-whatsapp\"></i>",
                            Link = "+989369043949",
                            Media = "Whatsapp"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "<i class=\"bi bi-instagram\"></i>",
                            Link = "https://www.instagram.com/leoneltech1?igsh=MXBycmQybXQ0bmVjaw==",
                            Media = "Instagram"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "<i class=\"bi bi-linkedin\"></i>",
                            Link = "https://www.linkedin.com/in/abbas-masoud-0681a5315?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_mdeium=android_app",
                            Media = "LinkedIn"
                        });
                });

            modelBuilder.Entity("InfoTech.Models.SubPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Author")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Keywords")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("SubPages");
                });

            modelBuilder.Entity("InfoTech.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Link = "https://www.youtube.com/watch?v=Cn4G2lZ_g2I",
                            Title = "َAbout Us Video"
                        });
                });

            modelBuilder.Entity("InfoTech.Models.WorkProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("DisplayOrder")
                        .HasColumnType("tinyint");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("WorkProcesses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "در یک ساعت آزاد، زمانی که قدرت انتخاب ما بی بند و بار است و",
                            DisplayOrder = (byte)1,
                            ImageId = 18,
                            Step = "یک سرویس را انتخاب کنید"
                        },
                        new
                        {
                            Id = 2,
                            Description = "در یک ساعت آزاد، زمانی که قدرت انتخاب ما بی بند و بار است و",
                            DisplayOrder = (byte)2,
                            ImageId = 19,
                            Step = "الزامات را تعریف کنید"
                        },
                        new
                        {
                            Id = 3,
                            Description = "در یک ساعت آزاد، زمانی که قدرت انتخاب ما بی بند و بار است و",
                            DisplayOrder = (byte)3,
                            ImageId = 20,
                            Step = "درخواست یک جلسه"
                        },
                        new
                        {
                            Id = 4,
                            Description = "در یک ساعت آزاد، زمانی که قدرت انتخاب ما بی بند و بار است و",
                            DisplayOrder = (byte)4,
                            ImageId = 21,
                            Step = "راه حل نهایی 3"
                        });
                });

            modelBuilder.Entity("InfoTech.Models.WorkTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EndDay")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("StartDay")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("WorkTimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDay = 4,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartDay = 0,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new TimeOnly(14, 0, 0),
                            StartDay = 5,
                            StartTime = new TimeOnly(8, 0, 0)
                        });
                });

            modelBuilder.Entity("InfoTech.Models.Brand", b =>
                {
                    b.HasOne("InfoTech.Models.Image", "Image")
                        .WithOne("Brand")
                        .HasForeignKey("InfoTech.Models.Brand", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("InfoTech.Models.HeroBanner", b =>
                {
                    b.HasOne("InfoTech.Models.Image", "Image")
                        .WithOne("HeroBanner")
                        .HasForeignKey("InfoTech.Models.HeroBanner", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("InfoTech.Models.Language", b =>
                {
                    b.HasOne("InfoTech.Models.Image", "Image")
                        .WithOne("Language")
                        .HasForeignKey("InfoTech.Models.Language", "ImageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("InfoTech.Models.Project", b =>
                {
                    b.HasOne("InfoTech.Models.Image", "Image")
                        .WithOne("Project")
                        .HasForeignKey("InfoTech.Models.Project", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoTech.Models.Service", "Service")
                        .WithMany("Projects")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("InfoTech.Models.Service", b =>
                {
                    b.HasOne("InfoTech.Models.Image", "Image")
                        .WithOne("Service")
                        .HasForeignKey("InfoTech.Models.Service", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("InfoTech.Models.SubPage", b =>
                {
                    b.HasOne("InfoTech.Models.Page", "Page")
                        .WithMany("SubPages")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("InfoTech.Models.WorkProcess", b =>
                {
                    b.HasOne("InfoTech.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("InfoTech.Models.Image", b =>
                {
                    b.Navigation("Brand");

                    b.Navigation("HeroBanner");

                    b.Navigation("Language");

                    b.Navigation("Project");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("InfoTech.Models.Page", b =>
                {
                    b.Navigation("SubPages");
                });

            modelBuilder.Entity("InfoTech.Models.Service", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
